//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrickBreaker.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BrickBreaker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream brickBreak {
            get {
                return ResourceManager.GetStream("brickBreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap dkball {
            get {
                object obj = ResourceManager.GetObject("dkball", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap dkpaddle2 {
            get {
                object obj = ResourceManager.GetObject("dkpaddle2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap donkeykong {
            get {
                object obj = ResourceManager.GetObject("donkeykong", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gaBackground2 {
            get {
                object obj = ResourceManager.GetObject("gaBackground2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gaball2 {
            get {
                object obj = ResourceManager.GetObject("gaball2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap galagaBack {
            get {
                object obj = ResourceManager.GetObject("galagaBack", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gapaddle2 {
            get {
                object obj = ResourceManager.GetObject("gapaddle2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap heart__2_ {
            get {
                object obj = ResourceManager.GetObject("heart__2_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;leaderboard&gt;
        ///  &lt;highscore&gt;
        ///    &lt;nickname&gt;The evil scary&lt;/nickname&gt;
        ///    &lt;score&gt; 666&lt;/score&gt;
        ///  &lt;/highscore&gt;
        ///  &lt;highscore&gt;
        ///    &lt;nickname&gt;The happy smiler&lt;/nickname&gt;
        ///    &lt;score&gt;545&lt;/score&gt;
        ///  &lt;/highscore&gt;
        ///  &lt;highscore&gt;
        ///    &lt;nickname&gt;The sucky gamer&lt;/nickname&gt;
        ///    &lt;score&gt;-999&lt;/score&gt;
        ///  &lt;/highscore&gt;
        ///  &lt;highscore&gt;
        ///    &lt;nickname&gt;The newborn baby&lt;/nickname&gt;
        ///    &lt;score&gt;-100&lt;/score&gt;
        ///  &lt;/highscore&gt;
        ///  &lt;highscore&gt;
        ///    &lt;nickname&gt;The ultimate scorer&lt;/nickname&gt;
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string leaderboard {
            get {
                return ResourceManager.GetString("leaderboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Level&gt;
        ///	&lt;test&gt;
        ///		&lt;Brick&gt;
        ///			&lt;x&gt;172&lt;/x&gt;
        ///			&lt;y&gt;465&lt;/y&gt;
        ///			&lt;hp&gt;5&lt;/hp&gt;
        ///			&lt;colour&gt;Color [Blue]&lt;/colour&gt;
        ///		&lt;/Brick&gt;
        ///		&lt;Brick&gt;
        ///			&lt;x&gt;280&lt;/x&gt;
        ///			&lt;y&gt;469&lt;/y&gt;
        ///			&lt;hp&gt;1&lt;/hp&gt;
        ///			&lt;colour&gt;Color [DarkOrange]&lt;/colour&gt;
        ///		&lt;/Brick&gt;
        ///		&lt;Brick&gt;
        ///			&lt;x&gt;344&lt;/x&gt;
        ///			&lt;y&gt;388&lt;/y&gt;
        ///			&lt;hp&gt;1&lt;/hp&gt;
        ///			&lt;colour&gt;Color [DarkOrange]&lt;/colour&gt;
        ///		&lt;/Brick&gt;
        ///		&lt;Brick&gt;
        ///			&lt;x&gt;414&lt;/x&gt;
        ///			&lt;y&gt;26&lt;/y&gt;
        ///			&lt;hp&gt;3&lt;/hp&gt;
        ///			&lt;colour&gt;Color [Aqua]&lt;/colour&gt;
        ///		&lt;/Brick&gt;
        ///		&lt;Brick&gt;
        ///			&lt;x&gt;358&lt;/x&gt;
        ///			&lt;y&gt;26&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string level1XML {
            get {
                return ResourceManager.GetString("level1XML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Level&gt;
        ///		&lt;Brick&gt;
        ///			&lt;x&gt;376&lt;/x&gt;
        ///			&lt;y&gt;22&lt;/y&gt;
        ///			&lt;hp&gt;5&lt;/hp&gt;
        ///			&lt;colour&gt;DarkOrchid&lt;/colour&gt;
        ///		&lt;/Brick&gt;
        ///		&lt;Brick&gt;
        ///			&lt;x&gt;302&lt;/x&gt;
        ///			&lt;y&gt;274&lt;/y&gt;
        ///			&lt;hp&gt;3&lt;/hp&gt;
        ///			&lt;colour&gt;DarkOrchid&lt;/colour&gt;
        ///		&lt;/Brick&gt;
        ///		&lt;Brick&gt;
        ///			&lt;x&gt;653&lt;/x&gt;
        ///			&lt;y&gt;22&lt;/y&gt;
        ///			&lt;hp&gt;3&lt;/hp&gt;
        ///			&lt;colour&gt;Gray&lt;/colour&gt;
        ///		&lt;/Brick&gt;
        ///		&lt;Brick&gt;
        ///			&lt;x&gt;562&lt;/x&gt;
        ///			&lt;y&gt;22&lt;/y&gt;
        ///			&lt;hp&gt;5&lt;/hp&gt;
        ///			&lt;colour&gt;Gray&lt;/colour&gt;
        ///		&lt;/Brick&gt;
        ///		&lt;Brick&gt;
        ///			&lt;x&gt;570&lt;/x&gt;
        ///			&lt;y&gt;272&lt;/y&gt;
        ///			&lt;hp&gt;5&lt;/hp&gt;
        ///			&lt;colour&gt;Red&lt;/colour [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string level2XML {
            get {
                return ResourceManager.GetString("level2XML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///.
        /// </summary>
        internal static string level3XML {
            get {
                return ResourceManager.GetString("level3XML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///.
        /// </summary>
        internal static string level4XML {
            get {
                return ResourceManager.GetString("level4XML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///.
        /// </summary>
        internal static string level5XML {
            get {
                return ResourceManager.GetString("level5XML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap menuBack {
            get {
                object obj = ResourceManager.GetObject("menuBack", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pacmanback {
            get {
                object obj = ResourceManager.GetObject("pacmanback", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream paddleHit {
            get {
                return ResourceManager.GetStream("paddleHit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pmBack {
            get {
                object obj = ResourceManager.GetObject("pmBack", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pmball3 {
            get {
                object obj = ResourceManager.GetObject("pmball3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pmpaddle2 {
            get {
                object obj = ResourceManager.GetObject("pmpaddle2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tetris {
            get {
                object obj = ResourceManager.GetObject("tetris", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap thefinalball {
            get {
                object obj = ResourceManager.GetObject("thefinalball", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tsback {
            get {
                object obj = ResourceManager.GetObject("tsback", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tsball {
            get {
                object obj = ResourceManager.GetObject("tsball", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tspaddle2 {
            get {
                object obj = ResourceManager.GetObject("tspaddle2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap zlbackground_1078__800_at__3__0_ {
            get {
                object obj = ResourceManager.GetObject("zlbackground_1078__800_at__3__0_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap zlpaddle {
            get {
                object obj = ResourceManager.GetObject("zlpaddle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
